"""initial schema

Revision ID: 202607240001
Revises:
Create Date: 2026-07-24 00:01:00

Hand-written (not autogenerated) to exactly mirror core/models/*.py at
project start. Future schema changes should use
`alembic revision --autogenerate -m "..."` and be reviewed by a human
before merging — autogenerate is good at diffing, not always at picking
the right migration operation (e.g. renames vs drop+add).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "202607240001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- assets -----------------------------------------------------------
    op.create_table(
        "assets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "category",
            sa.Enum(
                "currency", "gold", "silver", "fuel", "crypto",
                name="asset_category",
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("name_ckb", sa.String(length=128), nullable=False),
        sa.Column("base_unit", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("code", name="uq_assets_code"),
    )
    op.create_index("ix_assets_code", "assets", ["code"])
    op.create_index("ix_assets_category", "assets", ["category"])

    # --- sources ------------------------------------------------------------
    op.create_table(
        "sources",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("provider_path", sa.String(length=256), nullable=False),
        sa.Column("trust_weight", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column(
            "status",
            sa.Enum("active", "degraded", "disabled", name="source_status"),
            nullable=False,
            server_default="active",
        ),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_sources_asset_id", "sources", ["asset_id"])

    # --- raw_readings ---------------------------------------------------------
    op.create_table(
        "raw_readings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sources.id", ondelete="CASCADE"), nullable=False),
        sa.Column("value", sa.Numeric(18, 6), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "reconciled", "rejected", name="reading_status"),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("raw_payload", postgresql.JSONB(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_raw_readings_asset_id", "raw_readings", ["asset_id"])
    op.create_index("ix_raw_readings_source_id", "raw_readings", ["source_id"])
    op.create_index("ix_raw_readings_status", "raw_readings", ["status"])
    op.create_index("ix_raw_readings_observed_at", "raw_readings", ["observed_at"])

    # --- published_rates -----------------------------------------------------
    op.create_table(
        "published_rates",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False),
        sa.Column("price", sa.Numeric(18, 6), nullable=False),
        sa.Column("price_per_gram", sa.Numeric(18, 6), nullable=True),
        sa.Column("daily_change_pct", sa.Numeric(9, 4), nullable=True),
        sa.Column("daily_change_abs", sa.Numeric(18, 6), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("published", "pending_review", "approved", "rejected", name="publication_status"),
            nullable=False,
            server_default="published",
        ),
        sa.Column("confidence_score", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("source_reading_ids", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=False, server_default="{}"),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by_admin_id", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciliation_meta", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_published_rates_asset_id", "published_rates", ["asset_id"])
    op.create_index("ix_published_rates_effective_at", "published_rates", ["effective_at"])
    op.create_index("ix_published_rates_status", "published_rates", ["status"])
    # Fast "latest rate per asset" lookups (bot's most common query).
    op.create_index(
        "ix_published_rates_asset_effective",
        "published_rates",
        ["asset_id", sa.text("effective_at DESC")],
    )

    # --- users --------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("language", sa.Enum("ckb", "en", "ar", name="language"), nullable=False, server_default="ckb"),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_blocked", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("telegram_id", name="uq_users_telegram_id"),
    )
    op.create_index("ix_users_telegram_id", "users", ["telegram_id"])

    # --- alerts -------------------------------------------------------------
    op.create_table(
        "alerts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False),
        sa.Column("threshold", sa.Numeric(18, 6), nullable=False),
        sa.Column("direction", sa.Enum("above", "below", name="alert_direction"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "triggered", "cancelled", name="alert_status"),
            nullable=False,
            server_default="active",
        ),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_alerts_user_id", "alerts", ["user_id"])
    op.create_index("ix_alerts_asset_id", "alerts", ["asset_id"])
    op.create_index("ix_alerts_status", "alerts", ["status"])

    # --- ai_summaries -------------------------------------------------------
    op.create_table(
        "ai_summaries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("summary_date", sa.Date(), nullable=False),
        sa.Column("language", sa.Enum("ckb", "en", "ar", name="language"), nullable=False, server_default="ckb"),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("source_rate_ids", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("generation_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("summary_date", name="uq_ai_summaries_date"),
    )
    op.create_index("ix_ai_summaries_summary_date", "ai_summaries", ["summary_date"])


def downgrade() -> None:
    op.drop_table("ai_summaries")
    op.drop_table("alerts")
    op.drop_table("users")
    op.drop_table("published_rates")
    op.drop_table("raw_readings")
    op.drop_table("sources")
    op.drop_table("assets")

    # Enum types created via sa.Enum(...) inside create_table are not
    # dropped automatically by drop_table on Postgres — drop explicitly so
    # downgrade is fully reversible.
    for enum_name in (
        "asset_category",
        "source_status",
        "reading_status",
        "publication_status",
        "language",
        "alert_direction",
        "alert_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
